language: go
go:
        - tip
sudo: false
services:
        - memcached
before_install:
        - go get -v github.com/golang/lint/golint
        - go get github.com/mattn/goveralls
        - go get github.com/axw/gocov/gocov
        - go get golang.org/x/tools/cmd/cover
        - go get golang.org/x/tools/cmd/vet
script:
        - $HOME/gopath/bin/golint .
        - go vet ./...
        - ./scripts/goveralls.sh
deploy:
        provider: openshift
        user: rocha.porto@gmail.com
        password:
                secure: KGNGEr3EMKusBJnDiOuQu6irnzdu4S2FeMDNInDNQJXtgeipN+ZeEWAdf61bFovviywHgfF++y0M/7M27g8G4xx7FmjgxT+bTGrpfXbQMdmsBvas85Vg2RWQ6zdro7tM4zEOlvQdU/7d9DSM6FeZR9+r3+9+bEFvyCstl8j+r0M=
        domain: ezgliding
        app:
                master: staging
